steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/feedshop:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/feedshop:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'feedshop'
      - '--image'
      - 'gcr.io/$PROJECT_ID/feedshop:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'SPRING_PROFILES_ACTIVE=prod'
      - '--set-env-vars'
      - 'GCS_ID=YOUR-NEW-PROJECT-ID'
      - '--set-env-vars'
      - 'GCS_BUCKET=feedshop-uploads'
      - '--set-env-vars'
      - 'DB_NAME=feedshop_db'
      - '--set-env-vars'
      - 'DB_USERNAME=cmall'
      - '--set-env-vars'
      - 'CDN_BASE_URL=https://cdn-feedshop.store'
      - '--set-env-vars'
      - 'MAIL_HOST=smtp.gmail.com'
      - '--set-env-vars'
      - 'MAIL_PORT=587'
      - '--set-secrets'
      - 'DB_PASSWORD=db-password:latest'
      - '--set-secrets'
      - 'MAIL_USERNAME=gmail-username:latest'
      - '--set-secrets'
      - 'MAIL_PASSWORD=gmail-password:latest'
      - '--set-secrets'
      - 'MAILGUN_API_KEY=mailgun-api-key:latest'
      - '--set-secrets'
      - 'MAILGUN_DOMAIN=mailgun-domain:latest'
      - '--set-secrets'
      - 'MAILGUN_EMAIL=mailgun-email:latest'
      - '--set-secrets'
      - 'RECAPTCHA_SECRET_KEY=recaptcha-secret:latest'
      - '--set-secrets'
      - 'JWT_SECRET=jwt-secret:latest'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest'
      - '--set-secrets'
      - 'GOOGLE_CLIENT_ID=google-client-id:latest'
      - '--set-secrets'
      - 'GOOGLE_CLIENT_SECRET=google-client-secret:latest'
      - '--set-secrets'
      - 'KAKAO_CLIENT_ID=kakao-client-id:latest'
      - '--set-secrets'
      - 'KAKAO_CLIENT_SECRET=kakao-client-secret:latest'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/feedshop:$COMMIT_SHA'