version: '3.8'

services:
  feedshop-backend:
    build: .
    container_name: feedshop-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - feedshop-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  feedshop-network:
    driver: bridge