version: '3.8'

services:
  feedshop-backend:
    build: .
    container_name: feedshop-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - feedshop-network
    restart: unless-stopped

networks:
  feedshop-network:
    driver: bridge